# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e437fced3f5d5abc23983574ba5185c6b265172bae9ea3a3b107c1da05d5bc23c8c86c065b9fe3249a2520869b6aa2e42d1186c57d423beb19d0e0685c194d4

test:
  secret_key_base: a2f7fc3744259a4e05c8eed4e9ed4e93c4c9ff9578dcf4851df9c2052de3c6d863272ce1a688ce664c483c94ead951aed3763df435aec36aa10dc9b277334059

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
